//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RichWeb.Mvc.Bootstrap {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BootstrapRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BootstrapRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RichWeb.Mvc.Bootstrap.BootstrapRes", typeof(BootstrapRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{ #Start }}
        ///&lt;div class=&quot;panel panel-default&quot;&gt;
        ///    &lt;div class=&quot;panel-heading&quot;&gt;
        ///        &lt;h4 class=&quot;panel-title&quot;&gt;
        ///            &lt;a class=&quot;accordion-toggle&quot; data-toggle=&quot;collapse&quot; href=&quot;#{{ Id }}&quot;&gt;{{ Title }}
        ///            &lt;i class=&quot;icon-sort-up pull-right&quot;&gt;&lt;/i&gt;
        ///            &lt;/a&gt;
        ///        &lt;/h4&gt;
        ///    &lt;/div&gt;
        ///    &lt;div id=&quot;{{ Id }}&quot; class=&quot;panel-collapse {{ State }}&quot;&gt;
        ///        &lt;div class=&quot;panel-body&quot;&gt;
        ///{{ /Start }}
        ///
        ///{{ #End }}
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///&lt;/div&gt;
        ///{{ /End }}.
        /// </summary>
        internal static string RightPanel {
            get {
                return ResourceManager.GetString("RightPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{ #Start }}
        ///    &lt;div class=&quot;tab-pane {{ State }}&quot; id=&quot;{{ Id }}&quot;&gt;
        ///{{ /Start }}
        ///        &lt;div class=&quot;panel&quot;&gt;
        ///            &lt;div class=&quot;panel-body&quot;&gt;
        ///                
        ///{{ #End }}
        ///            &lt;/div&gt;
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///{{ /End }}
        ///
        ///.
        /// </summary>
        internal static string TabPane {
            get {
                return ResourceManager.GetString("TabPane", resourceCulture);
            }
        }
    }
}
